-- MySQL Script generated by MySQL Workbench
-- среда, 05. фебруар 2020. 20:09:50 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`IP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`IP` ;

CREATE TABLE IF NOT EXISTS `mydb`.`IP` (
  `idpregleda` INT NOT NULL,
  `JMBG` VARCHAR(245) NULL,
  `Simptomi` VARCHAR(245) NULL,
  `Tretman` VARCHAR(245) NULL,
  `Doktor` VARCHAR(145) NULL,
  `Datum` VARCHAR(45) NULL,
  `DN` VARCHAR(345) NULL,
  `Disease` VARCHAR(145) NULL,
  PRIMARY KEY (`idpregleda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Karton`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Karton` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Karton` (
  `idkarton` INT NOT NULL,
  `Ime` VARCHAR(45) NULL,
  `Prezime` VARCHAR(45) NULL,
  `Godina` VARCHAR(45) NULL,
  `Adresa` VARCHAR(145) NULL,
  `Telefon` VARCHAR(45) NULL,
  `Mail` VARCHAR(45) NULL,
  `zaduzenilekar` VARCHAR(45) NULL,
  `JMBG` VARCHAR(13) NULL,
  `Pol` VARCHAR(45) NULL,
  `Rasa` VARCHAR(45) NULL,
  PRIMARY KEY (`idkarton`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
